image = "/capstor/scratch/cscs/dealmeih/images/mlperf-training-v4.0-nvidia-gpt3-24.04.pl224.sqsh"
# image = "/capstor/scratch/cscs/dealmeih/images/mlperf-training-v4.0-nvidia-gpt3-24.07.sqsh"

mounts = ["/capstor", "/users",
    "/capstor/scratch/cscs/dealmeih/nccl_plugin_todi/1.6.0-hcopy/libnccl-net.so:/usr/lib/libnccl-net-ofi.so",
    # "/capstor/scratch/cscs/manitart/nccl_plugin_todi/1.6.0/libnccl-net.so:/usr/lib/libnccl-net-ofi.so",
	# "/usr/lib64/libhwloc.so.15:/usr/lib/libhwloc.so.15",
	# "/usr/lib64/libpciaccess.so.0:/usr/lib/libpciaccess.so.0",
	# "/usr/lib64/libxml2.so.2:/usr/lib/libxml2.so.2"
]

writable = true

[annotations]
# com.hooks.dcgm.enabled = "true"
com.hooks.cxi.enabled = "true"

[env]
CUDA_CACHE_DISABLE = "1"
NCCL_NET = "AWS Libfabric"
NCCL_CROSS_NIC = "1"
NCCL_NET_GDR_LEVEL = "PHB"
# NCCL_SOCKET_IFNAME = "hsn"  ###
NCCL_NET_PLUGIN = "ofi"
# NCCL_IGNORE_CPU_AFFINITY = "1"  ###
# NCCL_SOCKET_NTHREADS = "1"  ###
# NCCL_NSOCKS_PERTHREAD = "1"  ###

FI_CXI_COMPAT = "0"  ###
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
FI_CXI_DEFAULT_CQ_SIZE = "131072"
FI_CXI_DEFAULT_TX_SIZE = "32768"
FI_CXI_RX_MATCH_MODE = "software"

MPICH_NO_BUFFER_ALIAS_CHECK = "1"
MPICH_OFI_NIC_POLICY = "NUMA"
MPICH_OFI_STARTUP_CONNECT = "1"
MPICH_SMP_SINGLE_COPY_MODE = "NONE"
MPICH_GPU_SUPPORT_ENABLED = "0"
MPICH_OFI_CXI_COUNTER_REPORT = "2"
MPICH_COLL_OPT_OFF = "mpi_allgather"

# NCCL_DEBUG_SUBSYS = "INIT,TUNING"
